"use client";

import { useMemo, useCallback, useEffect, useRef, useState } from "react";
import { AgGridReact } from "ag-grid-react";
import {
  ModuleRegistry,
  AllCommunityModule,
  type ColDef,
  type GetRowIdParams,
  type RowClassParams,
  type GridApi,
} from "ag-grid-community";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-quartz.css";
import { AlertTriangle } from "lucide-react";
import { useUiStore } from "@/stores/useUiStore";
import { SeverityPill } from "@/components/shared/StatusPill";
import { SOURCE_LABEL, REASON_LABEL, type ReconciliationItem } from "@/lib/types";

ModuleRegistry.registerModules([AllCommunityModule]);

function SeverityCell({ data }: { data: ReconciliationItem }) {
  return <SeverityPill severity={data.severity} />;
}

function VarianceCell({ data }: { data: ReconciliationItem }) {
  const color =
    data.severity === "critical"
      ? "text-status-critical"
      : data.severity === "high"
        ? "text-status-high"
        : data.severity === "medium"
          ? "text-status-medium"
          : "text-status-low";
  return (
    <span className={`tabular-nums font-medium ${color}`}>
      {data.severity === "critical" && <AlertTriangle size={12} className="mr-1 inline -mt-0.5" />}
      {data.variancePct.toFixed(1)}%
      <span className="ml-1 font-normal text-text-secondary">({data.unitDelta > 0 ? "+" : ""}{data.unitDelta}u)</span>
    </span>
  );
}

function ImpactCell({ data }: { data: ReconciliationItem }) {
  return (
    <span className="tabular-nums font-medium text-text-primary">
      ${data.impactValue.toLocaleString()}
    </span>
  );
}

function SourceQtyCell({ data }: { data: ReconciliationItem }) {
  return (
    <div className="flex gap-3 tabular-nums">
      {(Object.keys(data.quantities) as (keyof typeof data.quantities)[]).map((src) => (
        <span
          key={src}
          className={src === data.outlier ? "font-semibold text-status-critical" : "text-text-secondary"}
          title={SOURCE_LABEL[src]}
        >
          {SOURCE_LABEL[src]}:{data.quantities[src]}
        </span>
      ))}
    </div>
  );
}

function AssigneeCell({ data }: { data: ReconciliationItem }) {
  if (!data.assignedTo) return <span className="text-text-secondary">Unassigned</span>;
  return <span className="text-text-primary">{data.assignedTo}</span>;
}

interface Props {
  items: ReconciliationItem[];
}

// Note: this uses AG Grid's v32.2+ object-form `rowSelection` config and
// the v33+ modular ModuleRegistry API (ag-grid-community ^35). The
// selection checkbox column is auto-generated by `rowSelection` itself —
// it is NOT declared as a manual colDef, since mixing the legacy
// checkboxSelection/headerCheckboxSelection colDef props with the new
// rowSelection object produces a duplicate/conflicting selection column.
// Pinning/sizing that auto column is done via `selectionColumnDef` below.
export function ReconciliationGrid({ items }: Props) {
  const theme = useUiStore((s) => s.theme);
  const openDrawer = useUiStore((s) => s.openDrawer);
  const setSelectedIds = useUiStore((s) => s.setSelectedIds);
  const selectedIds = useUiStore((s) => s.selectedIds);
  const [mounted, setMounted] = useState(false);
  const gridApiRef = useRef<GridApi<ReconciliationItem> | null>(null);
  useEffect(() => setMounted(true), []);

  // clearSelection() (called after a resolve/bulk action, or by the
  // "Clear" button) only ever updated the Zustand mirror of the selection.
  // AG Grid keeps its OWN internal selection state, which nothing was
  // telling to actually uncheck — most visibly for "Request manual count",
  // which doesn't remove any rows, so the checkboxes stayed checked while
  // the "N selected" bar vanished, only to reappear with a stale count the
  // next time the user selected a different row. Watching for the store's
  // selection dropping to zero and mirroring that into the grid keeps both
  // in sync regardless of which side triggered the change.
  useEffect(() => {
    if (selectedIds.length === 0) gridApiRef.current?.deselectAll();
  }, [selectedIds]);

  const getRowId = useCallback((params: GetRowIdParams<ReconciliationItem>) => params.data.id, []);

  const columnDefs = useMemo<ColDef<ReconciliationItem>[]>(
    () => [
      { field: "sku", headerName: "Code", width: 120, cellClass: "tabular-nums font-medium" },
      { field: "product", headerName: "Product", flex: 1, minWidth: 190 },
      { field: "location", headerName: "Place", width: 130 },
      { headerName: "Counts in each notebook", flex: 1.3, minWidth: 210, cellRenderer: SourceQtyCell, sortable: false },
      {
        headerName: "Money gap",
        width: 100,
        cellRenderer: ImpactCell,
        sort: "desc",
        comparator: (a, b) => a - b,
        valueGetter: (p) => p.data?.impactValue,
      },
      {
        headerName: "How far apart",
        width: 140,
        cellRenderer: VarianceCell,
        comparator: (a, b) => a - b,
        valueGetter: (p) => p.data?.variancePct,
      },
      { headerName: "How serious", width: 130, cellRenderer: SeverityCell, valueGetter: (p) => p.data?.severity },
      { headerName: "Who is on it", width: 130, cellRenderer: AssigneeCell, valueGetter: (p) => p.data?.assignedTo },
      {
        field: "suggestedReason",
        headerName: "Likely reason",
        width: 160,
        valueFormatter: (p) => REASON_LABEL[p.value as keyof typeof REASON_LABEL],
      },
      {
        field: "lastSeen",
        headerName: "Last seen",
        width: 100,
        valueFormatter: (p) => new Date(p.value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
        cellClass: "tabular-nums text-text-secondary",
      },
    ],
    []
  );

  const defaultColDef = useMemo<ColDef>(
    () => ({ resizable: true, sortable: true, filter: false, suppressMovable: true }),
    []
  );

  const getRowClass = useCallback((params: RowClassParams<ReconciliationItem>) => {
    const isNew = params.data && Date.now() - new Date(params.data.lastSeen).getTime() < 8000;
    return isNew ? "animate-row-in" : undefined;
  }, []);

  if (!mounted) {
    return <div className="h-[560px] w-full animate-pulse rounded-card border border-border bg-surface" />;
  }

  return (
    <div className={`ag-theme-quartz ag-theme-stocksync ${theme === "dark" ? "ag-theme-quartz-dark" : ""}`} style={{ height: 560 }}>
      <AgGridReact<ReconciliationItem>
        rowData={items}
        columnDefs={columnDefs}
        defaultColDef={defaultColDef}
        getRowId={getRowId}
        onGridReady={(e) => {
          gridApiRef.current = e.api;
        }}
        rowSelection={{ mode: "multiRow", checkboxes: true, headerCheckbox: true }}
        selectionColumnDef={{ pinned: "left", width: 44, sortable: false }}
        onSelectionChanged={(e) => setSelectedIds(e.api.getSelectedRows().map((r) => r.id))}
        onRowClicked={(e) => {
          // Guard against the checkbox cell's click bubbling up as a row
          // click — without this, selecting a row for a bulk action also
          // pops the detail drawer open every time.
          const target = e.event?.target as HTMLElement | null;
          if (target?.closest('input[type="checkbox"], .ag-selection-checkbox')) return;
          if (e.data) openDrawer(e.data.id);
        }}
        getRowClass={getRowClass}
        animateRows
        theme="legacy"
      />
    </div>
  );
}
